import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import CssBaseline from "@mui/material/CssBaseline";
import { Zen_Dots } from 'next/font/google';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme';
import Container from "@mui/material/Container";
import Navbar from './(components)/Navbar';

const zen_dots = Zen_Dots({
  weight: "400",
  variable: '--font-zen-dots',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={zen_dots.variable} style={{ height: "100%" }}>
      <body style={{ height: "100%" }}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <Container maxWidth="xl" sx={{ height: "100%" }}>
              <Navbar/>
              <Container sx={{ height: "100%" }}>
                {children}
              </Container>
            </Container>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
